### ISSUE TITLE
[FR]-The imports should be compatible with different datetime formats.

### ISSUE THREAD

**Issue by karan100010** [hackergram/sakhacabs#264]
**Is your feature request related to a problem? Please describe.**
Unable to import a booking from a .xlsx file because the dispatcher comes with error due to the date formatting of the file. So dispatcher should automatically convert the random date format to a specific date format and upload the file.

**Comment by arjunvenkatraman** [comment]
Look at the API (will go over this once your setup is done). At the point where we're taking the date input we are expecting it as a string in YYYY-MM-DD HH:MM:SS format. The UI should manipulate the input data to fit the API's needs. Moment.js can help. We already have it included.

**Comment by arjunvenkatraman** [comment]
Have separated the fields for pickup time and pickup date. This way, the user has more control also, this seems tor eflect the test data more accurately. Please test with few different input formats.
Caveat - Some formats will need hand management before import. This is because certain formats have special characters and other such issues. Formats will have to be seen on a case by case basis. If a particular format warrants special automation, will address that in a future release.
