### ISSUE TITLE
[FR]-There should be the new section for remarks on each document create/edit form

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#265]
The dispatcher UI should have new section to enter remarks, on the every create/edit form or whenever a file is imported

**Comment by arjunvenkatraman** [comment]
@karan100010  to fix - Here we need to build the entire forms for customer edit and product edit. This is being done using modals in the dispatcher window. Suggest add the same modals to the Manage <Document> pages, so that we have consistency. Also the manage pages should be the default go to place for editing things. Eventually that entire dashboard has to be replaced with a Vue.js setup....but for now, just go with copying over the modals and making the links on the datatables with the icons, so that users can edit individual records on all documents. File a separate FR for each one to be made so that we can track better.
