### ISSUE TITLE
[BUG]-V1.01 Feedback Regression Testing- Unable to import a booking file with different date format in dispatcher 

### ISSUE THREAD

**Issue by suryaveer5320129** [hackergram/sakhacabs#317]
**Describe the bug**
Unable to import a booking file with different date format in dispatcher 

**To Reproduce**
same as normal

**Expected behavior**
It should import the file

**Screenshots**
Na

**Desktop (please complete the following information):**
na

**Smartphone (please complete the following information):**
na

**Additional context**
This is the file i tried to import 
[test import.xlsx](https://github.com/hackergram/sakhacabs/files/2751726/test.import.xlsx)

**Comment by suryaveer5320129** [comment]
I think all the formats available in this https://www.ibm.com/support/knowledgecenter/en/SSLVMB_23.0.0/spss/base/syn_date_and_time_date_time_formats.html could be incorporated

**Comment by arjunvenkatraman** [comment]
What does "different" mean? "Different" from what? Which formats are working, which are not working. Please provide a detailed list/table!

**Comment by arjunvenkatraman** [comment]
The test file you have provided appears to be created on LibreOffice. Creating a Timestamp with hh:mm:ss format in LibreOffice and then importing seems to  be failing. The same data when copy pasted into google spreadsheets, downloaded as xslx and imported, works. 
Closing this since Linux is not the OS in use at the client, However, please keep a watch out for similar issues. Also, please save the same file in xlsx format using Microsoft Excel and then try importing. 
@suryaveer5320129

**Comment by arjunvenkatraman** [comment]
Please file a separate issue for each file that is failing and provide the JSON output as part of the bug.
@suryaveer5320129  @karan100010 please watch
